### ISSUE TITLE
ENV['SEMIAN_SEMAPHORES_DISABLED'] and SEM_UNDO

### ISSUE THREAD

**Issue by smitchelus** [Shopify/semian#129]
Hi, I'm trying to get my head around the relationship between the "SEMIAN_SEMAPHORES_DISABLED" environment variable whether semaphores are actually utilized by the library. I wholeheartedly admit that most of my confusion is due to my lack of understanding about Ruby's C extensions, so my apologies for that. Here's my question though...

If I set SEMIAN_SEMAPHORES_DISABLED=1 then the following if statement should execute the else block:

https://github.com/Shopify/semian/blob/master/lib/semian.rb#L177
```
if Semian.semaphores_enabled?
  require 'semian/semian'
else
  Semian::MAX_TICKETS = 0
end
```
If that's the case does that mean that the C extension code is not pulled in? Assuming yes, does that mean that semaphore calls will not be performed? 

Ultimately, I ask this to determine whether the SEM_UNDO threading issue would be avoided in this case. Am I barking up the wrong tree?

**Comment by dalehamel** [comment]
hi @smitchelus 

The block you reference is a platform-specific guard. If you see https://github.com/Shopify/semian/blob/master/lib/semian/platform.rb, you can see where `Semian.semaphores_enabled?` is defined. Basically, right now this is just to let you use semian on a non-linux platform (though it is more or less useless in that case). For us, this is mostly so that developers can use semian on their OS X laptops without having to change the project dependencies (I believe).

> If that's the case does that mean that the C extension code is not pulled in? Assuming yes, does that mean that semaphore calls will not be performed?

Yes, pretty much. If you look at the [rakefile](https://github.com/Shopify/semian/blob/master/Rakefile#L23) you will see that we have this same check before we compile the C extension (which only works on linux).

> Ultimately, I ask this to determine whether the SEM_UNDO threading issue would be avoided in this case. Am I barking up the wrong tree?

Currently the SEM_UNDO in the README is a caution that if you are using semian with the workers running in different threads (not different processes) they may leave the semaphore in a corrupt state if they are killed uncleanly. You can avoid this issue by having each worker be its own process, but that may not be possible given your environment. 

The SEM_UNDO process limitation is because this is built on top of the SysV IPC semaphores, and they can only undo operations at the process level. 

Does that answer your question @smitchelus ?

**Comment by smitchelus** [comment]
Hi Dale, that helps. I have one follow up question. We are a multi-threaded environment (which is why the question comes up), and I now see that the gem will get build with the C extension included in our Linux environments (thanks for the rakefile pointer). 

However, it still isn't quite clear to me what the role of the SEMIAN_SEMAPHORES_DISABLED environment variable is. It looks to me like that would prevent the extension from being loaded at runtime even though it was compiled. Is that correct?

**Comment by dalehamel** [comment]
> However, it still isn't quite clear to me what the role of the SEMIAN_SEMAPHORES_DISABLED environment variable is. It looks to me like that would prevent the extension from being loaded at runtime even though it was compiled. Is that correct?

Yes, but I assume this would never be done in production, as that would prevent semian from doing anything.

**Comment by smitchelus** [comment]
Oh, I thought the semaphores were just used for the bulkheading functionality. We're really just using the circuit breaker aspect of it for our use case. I thought those counters we tracked by plain ol' Ruby code ([SlidingWindow](https://github.com/Shopify/semian/blob/master/lib/semian/simple_sliding_window.rb) and [State](https://github.com/Shopify/semian/blob/master/lib/semian/simple_state.rb)).

**Comment by dalehamel** [comment]
> Oh, I thought the semaphores were just used for the bulkheading functionality.

Disclaimer: I'm only working on the C extension code and semian resources. I'm not sure how much of the rubyland functionality for semian works

**Comment by smitchelus** [comment]
Gotcha, fair enough. Thanks so much for your responsiveness so far. I'm going to throw my app/specs into a Docker container (I develop on a Mac) and test it with the environment variable set and see if it still triggers the circuit breaker. I'll update this issue with my findings.

**Comment by dalehamel** [comment]
Thanks! Sorry i don't have time to investigate this at the moment

**Comment by smitchelus** [comment]
OK, so this looks promising. We've built a small facade around Semian to insulate our services from the implementation details. I setup a Docker environment and ran the specs for our facade with the environment variable set. Here's the results from the relevant specs. We are warned that semaphores are disabled, but all the specs pass (with evidence of the circuit opening). 

```
I, [2017-03-17T00:47:15.163499 #83]  INFO -- : Semian semaphores are disabled, is this what you really want? - all operations will no-op

CircuitBreaker
  .attempt
I, [2017-03-17T00:47:26.350975 #83]  INFO -- : [Semian::CircuitBreaker] State transition from closed to open. success_count=0 error_count=1 success_count_threshold=1 error_count_threshold=1 error_timeout=1 error_last_at=""
timeout
    wraps errors when Semian throws errors
    does not open circuit for unexpected error types
    does not interrupt successful calls
I, [2017-03-17T00:47:26.371716 #83]  INFO -- : [Semian::CircuitBreaker] State transition from closed to open. success_count=0 error_count=1 success_count_threshold=1 error_count_threshold=1 error_timeout=1 error_last_at=""
timeout
    wrapped errors preserve the original error message
```

**Comment by sirupsen** [comment]
@smitchelus you'll be interested in https://github.com/Shopify/semian/pull/123 as well. It should make it in soon, hopefully

**Comment by smitchelus** [comment]
Thanks @sirupsen, I'll keep an eye on that one. I won't be at the conference I'm afraid. 

We have other use cases that would benefit from the bulkheading capability, but given that we're a multi-threaded environment it doesn't look like we'll be able to utilize that. 

As far as you know does my belief that the circuit breaker functionality is actually thread safe when the semphores are disabled sound correct to you?

**Comment by sirupsen** [comment]
@smitchelus I don't think the circuit breaker is thread-safe, but I also don't think it's a problem in most deployments if you're using MRI. That said, if you add threading support (and enable it by default) by providing mutexes around the sliding window and the counters, I'd happily accept it!

We talked about bulkheading for threaded apps, and it's something that'll benefit us internally as well for other apps than those using Unicorn. It might actually work with a webserver like Puma, we just haven't tested it. There's not really a reason why it wouldn't other than `SEM_UNDO` being set and not shutting down when a thread is killed, but I'm not sure that even matters as Puma or other threaded web-servers will just spawn a new thread. The important thing is that each thread will register the worker (if you're using quotas, on master). If you're using static ticket counts, I don't really see any problems with using it in a threaded environment.
