### ISSUE TITLE
Bump version to 0.6.3?

### ISSUE THREAD

**Issue by bibstha** [Shopify/semian#133]
Hi guys,
Since there's been quite some changes between https://github.com/Shopify/semian/compare/v0.6.2...a58a1c7 will you guys release a new version soon?

**Comment by dalehamel** [comment]
@bibstha we are testing the changes that have been merged to master by rolling them out to production internally. We intend to likely do a major version bump to 0.7.0 very soon, but we want to make sure that everything is stable before we do so.

0.6.2 is still stable and well tested, 0.7.0 will be released hopefully this week.

**Comment by sirupsen** [comment]
Yeah, let's merge 0.7.0 by the end of the week.

Until now, use latest master or 0.6.2.

**Comment by bibstha** [comment]
Sounds great. Thanks.

**Comment by dalehamel** [comment]
@bibstha FYI https://github.com/Shopify/semian/pull/140 is open and all code has been battle-hardened in production.

I'm hoping to get this officially released next week.

**Comment by bibstha** [comment]
Thanks. Closing this in favour of the 0.7.0
