### ISSUE TITLE
Platform check not sufficiently permissive

### ISSUE THREAD

**Issue by eapache** [Shopify/semian#15]
@Sirupsen @csfrancis I was trying to use semian on an x64 Ubuntu 14.10 installation and I got `Semian is not supported on x86_64-linux-gnu - all operations will no-op`

The current check is just `end_with?('-linux')` which clearly isn't sufficient, though I don't know enough about the format of `RUBY_PLATFORM` to say what else is needed.

**Comment by csfrancis** [comment]
Oh interesting. I could change the platform check to a regex: `/-linux(?:-gnu)?$/`.

Thoughts?

**Comment by eapache** [comment]
I have tried and failed to find an explanation of the format of `RUBY_PLATFORM` anywhere... although I did discover that it just says `java` on JRuby regardless of actual OS, so maybe it's not the best indicator in the first place...

**Comment by Sirupsen** [comment]
We could just do `/linux/`?

**Comment by eapache** [comment]
Works for me
