### ISSUE TITLE
When using the quota option, how is the total tickets available count calculated?

### ISSUE THREAD

**Issue by tboyko** [Shopify/semian#178]
Using the `quota` option effectively sets the `tickets` option to a percentage of the total tickets available. How is this total ticket count determined by semian if using, for instance, the `net_http` adapter?

**Comment by sirupsen** [comment]
Each process [registers itself](https://github.com/Shopify/semian/blob/master/ext/semian/sysv_semaphores.c#L62) the first time it uses the resource. If you have 10 processes using `net_http`, the first time they do the `net_http` call—they'll register. The tickets are automatically adjusted to respect the ratio ([rounding up](https://github.com/Shopify/semian/blob/master/ext/semian/tickets.c#L74)) every time the resource is claimed, based on the # of workers (if it changed).
