### ISSUE TITLE
concurrent-ruby

### ISSUE THREAD

**Issue by staugaard** [Shopify/semian#19]
Is there any reason you are not using the semaphore implementation from concurrent-ruby?
https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/atomic/semaphore.rb

It would give semian support for more rubies.

**Comment by byroot** [comment]
Hi @staugaard.

The reason why we use SysV Semaphores is because we run our app with unicorn. So we can't share a semaphore between multiple processes with the implementation you linked to.

For people running multithreaded servers though, it could be a fine solution.

**Comment by staugaard** [comment]
I see. Thanks.

**Comment by byroot** [comment]
We might add support for that in the future once the API is stabilized. But for now we have quite a lot of code to extract and document. 

Feel free to let this issue open if you'd like to use Semian in the future.

**Comment by Sirupsen** [comment]
@staugaard if you are using JRuby or other Ruby with parallelism you could definitely use a pure Ruby semaphore. We'd definitely accept a patch to make the semaphores pluggable.
