### ISSUE TITLE
Postgresql Adapter

### ISSUE THREAD

**Issue by supantha** [Shopify/semian#218]
Is there any reason for not having an adapter for postgresql?

**Comment by sirupsen** [comment]
@supantha nope, feel free to add one. We don't use Postgres at Shopify--so we haven't needed it, but I'm sure other users of Semian would appreciate it :)

**Comment by miry** [comment]
@mschoenlaub That is a great work. I am going to update README to link it.

**Comment by miry** [comment]
Added line of postgres adpter in Readme.
