### ISSUE TITLE
Adapters should be loaded automatically

### ISSUE THREAD

**Issue by michaelkipper** [Shopify/semian#226]
A conversation with @rafaelfranca turned into: Why not have the "built-in" adapters load automatically?

This would be a breaking change but would reduce the barrier to verifying that Semian is being used correctly.

WDYT?

cc: @sirupsen, @csfrancis, @fw42

**Comment by fw42** [comment]
I don't have a strong opinion, but as far as I know just loading the adapter doesn't actually enable any functionality yet (that has to be done via passing in configuration options when initializing the clients, right?).

**Comment by michaelkipper** [comment]
So it seems that looking for runtime logs of type `Semian is not configured for #{self.class.name}: #{semian_identifier}"` would be the best course of action. Having adapters load automatically would just increase log noise, and not actually enable Semians.
