### ISSUE TITLE
Semian sysv semaphores are not supported on x86_64-darwin21 

### ISSUE THREAD

**Issue by bsandeepan** [Shopify/semian#313]
While trying to figure out how to use Semian NetHTTP adapter, I found this INFO log.
`INFO -- : Semian sysv semaphores are not supported on x86_64-darwin21 - all operations will no-op`

I was not sure whether this is concerning, so I opened an issue.

**Comment by miry** [comment]
Working on example in https://github.com/Shopify/semian/pull/413
