### ISSUE TITLE
Update all development / test gems 

### ISSUE THREAD

**Issue by miry** [Shopify/semian#383]
There are plenty new versions of gems that are outdated:

- hiredis-client - #376
- redis - #385
- minitest - #375 
- rubocop - #384 
- rubocop-minitest - #380 
- rubocop-shopify - #378

**Comment by muz** [comment]
@miry I've updated the ticket description to link to respective Dependabot PRs for the testing deps.

In the case of the two that couldn't be merged as-is, I've added a commit to get the code to conform with the new enforced-linting style those gem bumps bring.
