### ISSUE TITLE
Detect Mysql2 connection errors

### ISSUE THREAD

**Issue by byroot** [Shopify/semian#39]
We should increment the errors count of the circuit breaker for MySQL connection errors (similar to https://github.com/Shopify/semian/pull/37)

But MySQL have only one exception class, so it's slightly dirty. Maybe we could improve the situation upstream.

Ref: https://github.com/brianmario/mysql2/issues/404

**Comment by Sirupsen** [comment]
This is how we currently do it (https://github.com/Shopify/shopify/blob/master/lib/patches/mysql_monitoring.rb#L23). We can also use the internal MySQL error numbers, however, there are multiple error numbers for the same string. It's been like this forever, so I doubt they'll change it upstream.

**Comment by byroot** [comment]
> This is how we currently do it 

For clarity:
```ruby
  rescue Mysql2::Error => error
     if error.message =~ /\ACan't connect to MySQL server on '.*' \(([0-9]+)\)\z/
       # do things
```
