### ISSUE TITLE
Travis CI: upgrade to new build infra

### ISSUE THREAD

**Issue by methodmissing** [Shopify/semian#68]
This warning is present in current builds:

```
This job ran on our legacy infrastructure. Please read our docs on how to upgrade`
```

See https://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by byroot** [comment]
IIRC we can't upgrade because we need sudo to install toxiproxy. @Sirupsen ?

**Comment by Sirupsen** [comment]
We could run it as a container though if they support that
