### ISSUE TITLE
Subscribe to 'resource timeout' exceptions

### ISSUE THREAD

**Issue by jacobbednarz** [Shopify/semian#79]
Heya,
I've implemented the instrumentation for keeping an eye on the status of semian adapters however one that would helpful to add would be the ['timed out waiting for resource'](https://github.com/Shopify/semian/blob/2a8503cf6667e7fc901b25de0ec51a78b667b53d/ext/semian/semian.c#L387) exceptions which are raised from the C extension. This would be handy to see when configuring ticket counts and trying to find that sweet spot for your application.

I'm not sure how to best achieve (or even if it's possible) but if someone would like to point me in the right direction, I'm more than happy to take a swing at it.

Thanks!

**Comment by byroot** [comment]
Unless I misunderstood your request, that is the `:busy` event: https://github.com/Shopify/semian/blob/2a8503cf6667e7fc901b25de0ec51a78b667b53d/lib/semian/protected_resource.rb#L28

**Comment by jacobbednarz** [comment]
Thanks for the confirmation - I thought that was the case too however on my side the events from the semian instrumentation didn't match up to what we are seeing in our exception tracker. There is a possibility there is something fishy going on with way the exception tracker is rolling up these errors so let me take a look into that and explore that further.
