### ISSUE TITLE
Opt out of ticket count feature

### ISSUE THREAD

**Issue by grollest** [Shopify/semian#95]
### What
It would be good to be able to configure semian without having to specify a ticket count, or to be able to explicitly disable the ticket count feature altogether.

### Why
You might not want to limit the number of concurrent requests to a resource. This is the case in shopify-app-store, where we don’t want to limit the number of concurrent requests to the Shopify API.

**Comment by grollest** [comment]
This functionality was also brought up in https://github.com/Shopify/shopify/pull/82152 

@BoGs did you get anywhere with the PR for `tickets=false` mentioned there?

**Comment by sirupsen** [comment]
Agree @grollest, Semian bulkheads are really hard to configure —most use-cases _only_ need circuit breakers.

**Comment by grollest** [comment]
Furthermore, the scope of the IPC namespace (wrt SysV semaphores) on Heroku left me scratching my head: "Do all the workers on a dyno share the same IPC namespace?". 

And then of course altering the number of workers per dyno (or threads per puma process) without a corresponding change to the number of tickets could severely impact capacity for the resource.

I know none of what I'm saying is new, just putting it down here for the record. Maybe I can put some time into implementing this feature.

**Comment by sirupsen** [comment]
@BoGs is on this, will be working on it after some other high-priority work
